# -*- mode: python -*-

block_cipher = None

a = Analysis(['environment_manager\\main.py'],
             pathex=[],
             binaries=None,
             datas=[('environment_manager\\*.enaml', '.'),
                    ('environment_manager\\images\\*.png','images'),
                    ],
             hiddenimports=[
                "enaml.core.parse_tab.lextab",
                "enaml.core.compiler_helpers",
                "enaml.core.compiler_nodes",
                "enaml.core.enamldef_meta",
                "enaml.core.template",
                "enaml.core.api",
                "enaml.widgets.api",
                "enaml.widgets.form",
                "from enaml.widgets.dialog",
                "enaml.layout.api",
                "enaml.stdlib",
                "enaml.stdlib.message_box",
                "enaml.icon",
                "enaml.image",
                "enaml.layout.layout_helpers",
                "enaml.styling",
                "enaml.widgets.container",
                "enaml.widgets.separator",
                "enaml.core.looper",
                "enaml.layout.layout_helpers",
                "enaml.widgets.container",
                "enaml.widgets.push_button",
                "enaml.core.dynamic_template",
                "enaml.widgets.check_box",
                "enaml.widgets.dialog",
                "enaml.widgets.html",
                "enaml.widgets.image_view",
                "enaml.widgets.label",
                "enaml.winutil",
             ],
             hookspath=[],
             runtime_hooks=['rthook_pyqt5.py'],
             excludes=None,
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

#exe = EXE(pyz,
#          a.scripts,
#          a.binaries,
#          a.zipfiles,
#          a.datas,
#          name='EnvMgr',
#          debug=True,
#          strip=None,
#          upx=False,
#          console=True,
#          )

exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='EnvMgr',
          debug=True,
          strip=None,
          upx=False,
          console=False,
          )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=None,
               upx=False,
               name='EnvMgr')
